"""added extra field in lawyer registration 5 at 4:48 9/26/2025

Revision ID: 01a19f0e71b7
Revises: 1c0d157dc0ad
Create Date: 2025-09-26 16:49:27.505516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01a19f0e71b7'
down_revision: Union[str, Sequence[str], None] = '1c0d157dc0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add as nullable
    op.add_column('lawyerRegistration5', sa.Column('map_location', sa.String(), nullable=True))

    # Step 2 (optional): Backfill data with default value (e.g., "Not provided")
    op.execute("UPDATE \"lawyerRegistration5\" SET map_location = 'Not provided' WHERE map_location IS NULL")

    # Step 3: Alter column to be NOT NULL
    op.alter_column('lawyerRegistration5', 'map_location', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyerRegistration5', 'map_location')
    # ### end Alembic commands ###
