"""added extra field in lawyer registration 1 at 3:19 9/5/2025

Revision ID: 1c0d157dc0ad
Revises: 773ca6363312
Create Date: 2025-09-25 15:27:44.140289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0d157dc0ad'
down_revision: Union[str, Sequence[str], None] = '773ca6363312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
