"""setup neon db

Revision ID: 7829bc16b7d8
Revises: 3e2a7700d291
Create Date: 2025-09-29 14:39:54.603661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7829bc16b7d8'
down_revision: Union[str, Sequence[str], None] = '3e2a7700d291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyerRegistration1', sa.Column('short_note', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyerRegistration1', 'short_note')
    # ### end Alembic commands ###
