"""lawyer registration update with CODEID

Revision ID: 9bc5e2a7f143
Revises: d7e3be908566
Create Date: 2025-09-26 18:31:43.912333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc5e2a7f143'
down_revision: Union[str, Sequence[str], None] = 'd7e3be908566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # lawyerRegistration1
    op.add_column(
        'lawyerRegistration1',
        sa.Column('code_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_lawyerRegistration1_code_id'), 'lawyerRegistration1', ['code_id'], unique=True)
    op.alter_column('lawyerRegistration1', 'code_id', server_default=None)

    # lawyerRegistration2
    op.add_column(
        'lawyerRegistration2',
        sa.Column('code_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_lawyerRegistration2_code_id'), 'lawyerRegistration2', ['code_id'], unique=True)
    op.alter_column('lawyerRegistration2', 'code_id', server_default=None)

    # lawyerRegistration3
    op.add_column(
        'lawyerRegistration3',
        sa.Column('code_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_lawyerRegistration3_code_id'), 'lawyerRegistration3', ['code_id'], unique=True)
    op.alter_column('lawyerRegistration3', 'code_id', server_default=None)

    # lawyerRegistration4
    op.add_column(
        'lawyerRegistration4',
        sa.Column('code_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_lawyerRegistration4_code_id'), 'lawyerRegistration4', ['code_id'], unique=True)
    op.alter_column('lawyerRegistration4', 'code_id', server_default=None)

    # lawyerRegistration5
    op.add_column(
        'lawyerRegistration5',
        sa.Column('code_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_lawyerRegistration5_code_id'), 'lawyerRegistration5', ['code_id'], unique=True)
    op.alter_column('lawyerRegistration5', 'code_id', server_default=None)

    # lawyerRegistration6
    op.add_column(
        'lawyerRegistration6',
        sa.Column('code_id', sa.String(), nullable=False, server_default=sa.text("gen_random_uuid()::text"))
    )
    op.create_index(op.f('ix_lawyerRegistration6_code_id'), 'lawyerRegistration6', ['code_id'], unique=True)
    op.alter_column('lawyerRegistration6', 'code_id', server_default=None)




def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lawyerRegistration6_code_id'), table_name='lawyerRegistration6')
    op.drop_column('lawyerRegistration6', 'code_id')
    op.drop_index(op.f('ix_lawyerRegistration5_code_id'), table_name='lawyerRegistration5')
    op.drop_column('lawyerRegistration5', 'code_id')
    op.drop_index(op.f('ix_lawyerRegistration4_code_id'), table_name='lawyerRegistration4')
    op.drop_column('lawyerRegistration4', 'code_id')
    op.drop_index(op.f('ix_lawyerRegistration3_code_id'), table_name='lawyerRegistration3')
    op.drop_column('lawyerRegistration3', 'code_id')
    op.drop_index(op.f('ix_lawyerRegistration2_code_id'), table_name='lawyerRegistration2')
    op.drop_column('lawyerRegistration2', 'code_id')
    op.drop_index(op.f('ix_lawyerRegistration1_code_id'), table_name='lawyerRegistration1')
    op.drop_column('lawyerRegistration1', 'code_id')
    # ### end Alembic commands ###
