"""creating lawyer registration6

Revision ID: abe22f4c3f89
Revises: 2b9aa1ebc219
Create Date: 2025-08-31 10:29:24.273732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abe22f4c3f89'
down_revision: Union[str, Sequence[str], None] = '2b9aa1ebc219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyerRegistration6',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lawyer_id', sa.String(), nullable=False),
    sa.Column('professional_associations', sa.String(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('awards', sa.JSON(), nullable=True),
    sa.Column('publications', sa.JSON(), nullable=True),
    sa.Column('created_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyerRegistration1.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lawyerRegistration6_id'), 'lawyerRegistration6', ['id'], unique=False)
    op.add_column('lawyerRegistration1', sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyerRegistration1', 'is_verified')
    op.drop_index(op.f('ix_lawyerRegistration6_id'), table_name='lawyerRegistration6')
    op.drop_table('lawyerRegistration6')
    # ### end Alembic commands ###
