"""adding rejected reson column

Revision ID: afc6ff648903
Revises: abe22f4c3f89
Create Date: 2025-08-31 10:47:24.890679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc6ff648903'
down_revision: Union[str, Sequence[str], None] = 'abe22f4c3f89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyerRegistration1', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyerRegistration1', 'rejection_reason')
    # ### end Alembic commands ###
