"""updated lawyer registration 3

Revision ID: b2aa771c3edf
Revises: fdf0a55dca45
Create Date: 2025-08-28 16:40:01.171673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2aa771c3edf'
down_revision: Union[str, Sequence[str], None] = 'fdf0a55dca45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyerRegistration3',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lawyer_id', sa.String(), nullable=False),
    sa.Column('practice_area', sa.String(), nullable=False),
    sa.Column('court_admitted_to', sa.String(), nullable=False),
    sa.Column('active_since', sa.Integer(), nullable=False),
    sa.Column('work_experience', sa.JSON(), nullable=False),
    sa.Column('created_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyerRegistration1.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_id')
    )
    op.create_index(op.f('ix_lawyerRegistration3_id'), 'lawyerRegistration3', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lawyerRegistration3_id'), table_name='lawyerRegistration3')
    op.drop_table('lawyerRegistration3')
    # ### end Alembic commands ###
