"""Add rate column to job_applications

Revision ID: ce10adc921a1
Revises: 8605e2a49da9
Create Date: 2025-10-22 19:32:23.108121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce10adc921a1'
down_revision: Union[str, Sequence[str], None] = '8605e2a49da9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_posts', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_posts', 'verified')
    # ### end Alembic commands ###
