"""initial baseline

Revision ID: d01a7ba12c3c
Revises: 
Create Date: 2025-10-22 18:26:05.136568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd01a7ba12c3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('rate', sa.Enum('GOOD_FIT', 'MAYBE', 'NOT_A_FIT', 'NOT_DECIDED', name='ratingenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'rate')
    # ### end Alembic commands ###
