"""updated lawyer registration 4

Revision ID: d6390f3af201
Revises: b2aa771c3edf
Create Date: 2025-08-28 16:47:01.233265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6390f3af201'
down_revision: Union[str, Sequence[str], None] = 'b2aa771c3edf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyerRegistration4',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lawyer_id', sa.String(), nullable=False),
    sa.Column('office_image', sa.String(), nullable=False),
    sa.Column('case_results', sa.JSON(), nullable=True),
    sa.Column('created_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyerRegistration1.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_id')
    )
    op.create_index(op.f('ix_lawyerRegistration4_id'), 'lawyerRegistration4', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lawyerRegistration4_id'), table_name='lawyerRegistration4')
    op.drop_table('lawyerRegistration4')
    # ### end Alembic commands ###
