"""latitude and longitude

Revision ID: d7e3be908566
Revises: 01a19f0e71b7
Create Date: 2025-09-26 17:08:17.475458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e3be908566'
down_revision: Union[str, Sequence[str], None] = '01a19f0e71b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Add columns as nullable first
    op.add_column('lawyerRegistration5', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('lawyerRegistration5', sa.Column('longitude', sa.String(), nullable=True))

    # Populate columns with a default value (for example, some fixed lat/lng)
    op.execute("""
        UPDATE "lawyerRegistration5"
        SET latitude = '37.4221', longitude = '-122.0841';
    """) 

    # Now alter columns to set NOT NULL constraint
    op.alter_column('lawyerRegistration5', 'latitude', nullable=False)
    op.alter_column('lawyerRegistration5', 'longitude', nullable=False)

    # Drop old column after
    op.drop_column('lawyerRegistration5', 'map_location')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyerRegistration5', sa.Column('map_location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('lawyerRegistration5', 'longitude')
    op.drop_column('lawyerRegistration5', 'latitude')
    # ### end Alembic commands ###
