"""adding description

Revision ID: e057ea0d9866
Revises: 7152f55b790d
Create Date: 2025-09-06 14:51:19.410543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e057ea0d9866'
down_revision: Union[str, Sequence[str], None] = '7152f55b790d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyerRegistration3', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyerRegistration3', 'description')
    # ### end Alembic commands ###
