"""updated lawyer registration 1 and 2

Revision ID: fdf0a55dca45
Revises: 
Create Date: 2025-08-28 15:40:12.807973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf0a55dca45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyerRegistration1',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('photo', sa.String(), nullable=False),
    sa.Column('created_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_lawyerRegistration1_email'), 'lawyerRegistration1', ['email'], unique=True)
    op.create_index(op.f('ix_lawyerRegistration1_id'), 'lawyerRegistration1', ['id'], unique=False)
    op.create_table('lawyerRegistration2',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lawyer_id', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('bar_details', sa.JSON(), nullable=False),
    sa.Column('languages_spoken', sa.String(), nullable=False),
    sa.Column('education', sa.JSON(), nullable=False),
    sa.Column('created_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_datetime', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyerRegistration1.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lawyer_id')
    )
    op.create_index(op.f('ix_lawyerRegistration2_id'), 'lawyerRegistration2', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lawyerRegistration2_id'), table_name='lawyerRegistration2')
    op.drop_table('lawyerRegistration2')
    op.drop_index(op.f('ix_lawyerRegistration1_id'), table_name='lawyerRegistration1')
    op.drop_index(op.f('ix_lawyerRegistration1_email'), table_name='lawyerRegistration1')
    op.drop_table('lawyerRegistration1')
    # ### end Alembic commands ###
